name: Java Test with TestLoginRunner

on:
  push:
    branches:
      - main  # Adjust branch name as per your main branch
  pull_request:
    branches:
      - main  # Adjust branch name as per your main branch

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Compile Java source
        run: |
          javac -cp "path/to/your/dependencies" UI_Automation_Project/src/test/java/UI_Automation_Project/login/TestLoginRunner.java
          # Replace "path/to/your/dependencies" with the actual path if there are dependencies

      - name: Run Java test
        run: |
          java -cp "path/to/compiled/classes:path/to/your/dependencies" UI_Automation_Project.src.test.java.UI_Automation_Project.login.TestLoginRunner
          # Adjust the class path and class name based on your project structure
          # Ensure you specify the correct classpath and class name with package structure

      - name: Upload test results
        uses: actions/upload-artifact@v2
        with:
          name: test-results
          path: path/to/your/test/reports  # Adjust path based on your test report location
