# name: Java Test with TestLoginRunner

# on:
#   push:
#     branches:
#       - main
#   pull_request:
#     branches:
#       - main

# jobs:
#   test:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v4
#         with:
#           token: ${{ secrets.GITHUB_TOKEN }}

#       - name: Set up JDK 11
#         uses: actions/setup-java@v4
#         with:
#           java-version: '11'
#           distribution: 'adopt'

#       - name: Navigate to project directory
#         run: cd UI_Automation_Project  # Adjust if your project directory is different

#       - name: Build and Test with Maven
#         run: |
#           mvn -f UI_Automation_Project/pom.xml clean test-compile -Dmaven.compiler.source=11 -Dmaven.compiler.target=11
#           mvn -f UI_Automation_Project/pom.xml test -Dtest=com.api.uiAutomation.UI_Automation_Project.login.TestLoginRunner -DfailIfNoTests=false
          
#       - name: Generate Karate HTML Reports
#         run: mvn -f UI_Automation_Project/pom.xml site -DskipTests=true -Dmaven.site.skip=true
#         continue-on-error: true

#       - name: Archive Karate HTML Reports
#         if: always()
#         uses: actions/upload-artifact@v4
#         with:
#           name: karate-reports
#           path: UI_Automation_Project/target/surefire-reports

name: Java Test with TestLoginRunner

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.0.0

      - name: API tests
        uses: erikbos/karate-action@main
        with:
          url: https://www.saucedemo.com/
          tests: UI_Automation_Project/src/test/java/UI_Automation_Project/login/TestLoginRunner.java
          output-directory: target/karate-reports  # Specify the output directory for Karate reports

      - name: List files in target/karate-reports
        run: ls -R target/karate-reports

      - name: Upload Test Reports
        uses: actions/upload-artifact@v4
        with:
          name: Karate Reports
          path: target/karate-reports  # Path to the directory where Karate reports are generated
