name: Java Test with TestLoginRunner

on:
  push:
    branches:
      - main  # Adjust branch name as per your main branch
  pull_request:
    branches:
      - main  # Adjust branch name as per your main branch

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Build with Maven
        run: mvn clean test-compile

      - name: Run TestLoginRunner
        run: mvn -Dtest=com.api.uiAutomation.UI_Automation_Project.login.TestLoginRunner test

      - name: Upload test results
        uses: actions/upload-artifact@v2
        with:
          name: test-results
          path: target/surefire-reports  # Adjust path based on your test report location
