name: Java Test with TestLoginRunner

on:
  push:
    branches:
      - main  # Adjust branch name as per your main branch
  pull_request:
    branches:
      - main  # Adjust branch name as per your main branch

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Navigate to project directory
        run: cd UI_Automation_Project  # Adjust if your project directory is different

      - name: Make directory to upload results
        run: mkdir -p testResults

      - name: Build and Test with Maven
        run: |
          mvn -f UI_Automation_Project/pom.xml clean test-compile -Dmaven.compiler.source=11 -Dmaven.compiler.target=11
          mvn -f UI_Automation_Project/pom.xml -Dtest=com.api.uiAutomation.UI_Automation_Project.login.TestLoginRunner test -DfailIfNoTests=false
          
      - name: Debug - List contents of target directory
        run: ls -R UI_Automation_Project/target

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: test-results
          # path: UI_Automation_Project/target/karate-reports  # Adjust path based on your test report location
          path: testResults
