name: Java Test with TestLoginRunner

on:
  push:
    branches:
      - main  # Adjust branch name as per your main branch
  pull_request:
    branches:
      - main  # Adjust branch name as per your main branch

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Navigate to project directory
        run: cd UI_Automation_Project  # Adjust if your project directory is different

      - name: Build and Test with Maven
        run: |
          mvn -f UI_Automation_Project/pom.xml clean test-compile -Dmaven.compiler.source=11 -Dmaven.compiler.target=11
          mvn -f UI_Automation_Project/pom.xml -Dtest=com.api.uiAutomation.UI_Automation_Project.login.TestLoginRunner test -DfailIfNoTests=false
          
      - name: Generate Karate HTML Reports
        run: mvn -f UI_Automation_Project/pom.xml verify

      - name: Archive Karate HTML Reports
        uses: actions/upload-artifact@v2
        with:
          name: karate-reports
          path: UI_Automation_Project/target/karate-reports
